version: '3.3'
services:
  dbserver:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: distribuida
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "c:/db-distribuida:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    expose:
      - 5432
  consul:
    image: consul:1.15.4
    command: |
      agent -dev
      -ui
      -bind 0.0.0.0
      -client 0.0.0.0
    ports:
      - "8500:8500"
    expose:
      - 8500
  proxy:
    image: traefik:v3.3.1
    command: |
      --api.insecure=true
      --providers.consulCatalog
      --providers.consulCatalog.exposedByDefault=false
      --providers.consulCatalog.refreshInterval=5s
      --providers.consulCatalog.endpoint.address=consul:8500
    ports:
      - "8080:8080"
      - "80:80"
    expose:
      - 80
    depends_on:
      - consul
  authors:
    image: reymon4/app_authors_grupal:latest
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbserver:5432/distribuida
      SERVER_PORT: 8080
      SPRING.CLOUD.CONSUL.HOST: consul
      SPRING.CLOUD.CONSUL.PORT: 8500

    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 1
  books:
    image: reymon4/app_books_grupal:latest
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbserver:5432/distribuida
      SERVER_PORT: 8080
      SPRING.CLOUD.CONSUL.HOST: consul
      SPRING.CLOUD.CONSUL.PORT: 8500
    depends_on:
      - dbserver
      - consul
      - authors
