receivers:
  otlp:
    protocols:
      http:
processors:
  batch:
exporters:
  jeager:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
extensions:
  health_check:
  pprof:
  zpages:
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
  traces:
    receivers: [otlp]
    processors: [batch]
    exporters: [jeager]