global:
  scrape_interval: 5s
  evaluation_interval: 5s


scrape_configs:
  - job_name: 'proxy'
    static_configs:
      - targets: [ 'proxy:8082' ]
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]